newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/5bs_es1.html'>5bs_es1.html</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/Accedi_ai_punteggi.html'>Accedi_ai_punteggi.html</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/Esempio_es.html'>Esempio_es.html</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/Esercizio_30102019.html'>Esercizio_30102019.html</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/Landi Anna Maria.html'>Landi Anna Maria.html</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/Landi.html'>Landi.html</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/Marketing.html'>Marketing.html</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/Programma.html'>Programma.html</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/punteggi.html'>punteggi.html</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/todo.html'>todo.html</a><br>"
                