newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/1929.html'>1929</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/Ciclo di vita.html'>Ciclo di vita</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/Es_Saraceno.html'>Es_Saraceno</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/Marketing operativo SINTESI.html'>Marketing operativo SINTESI</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/Marketing.html'>Marketing</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/marketing_mix.html'>marketing_mix</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/Progetto_Content_Marketing.html'>Progetto_Content_Marketing</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/punteggi.html'>punteggi</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/Punteggi_Sito.html'>Punteggi_Sito</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/SWOT.html'>SWOT</a><br>"
                