newlinks_4ce.innerHTML += "<a href='Programmi20192020/text_4ce/10_DOMANDE_BILANCIO.html'>10_DOMANDE_BILANCIO</a><br>"
                newlinks_4ce.innerHTML += "<a href='Programmi20192020/text_4ce/4ce_test2.html'>4ce_test2</a><br>"
                newlinks_4ce.innerHTML += "<a href='Programmi20192020/text_4ce/access_page.html'>access_page</a><br>"
                newlinks_4ce.innerHTML += "<a href='Programmi20192020/text_4ce/Bilancio.html'>Bilancio</a><br>"
                newlinks_4ce.innerHTML += "<a href='Programmi20192020/text_4ce/Bilancio_1.html'>Bilancio_1</a><br>"
                newlinks_4ce.innerHTML += "<a href='Programmi20192020/text_4ce/compiti.html'>compiti</a><br>"
                newlinks_4ce.innerHTML += "<a href='Programmi20192020/text_4ce/Conti_Risposta_Multipla.html'>Conti_Risposta_Multipla</a><br>"
                newlinks_4ce.innerHTML += "<a href='Programmi20192020/text_4ce/Es_conti_2020_1.html'>Es_conti_2020_1</a><br>"
                newlinks_4ce.innerHTML += "<a href='Programmi20192020/text_4ce/Es_Partitario.html'>Es_Partitario</a><br>"
                newlinks_4ce.innerHTML += "<a href='Programmi20192020/text_4ce/Finanziamenti.html'>Finanziamenti</a><br>"
                newlinks_4ce.innerHTML += "<a href='Programmi20192020/text_4ce/Pagina_Personale.html'>Pagina_Personale</a><br>"
                newlinks_4ce.innerHTML += "<a href='Programmi20192020/text_4ce/punteggi.html'>punteggi</a><br>"
                