newlinks_5ce.innerHTML += "<a href='Programmi20192020/text_5ce/5CE_testbp2.html'>5CE_testbp2</a><br>"
                newlinks_5ce.innerHTML += "<a href='Programmi20192020/text_5ce/Bilancio.html'>Bilancio</a><br>"
                newlinks_5ce.innerHTML += "<a href='Programmi20192020/text_5ce/BUDGET.html'>BUDGET</a><br>"
                newlinks_5ce.innerHTML += "<a href='Programmi20192020/text_5ce/Budget_es2.html'>Budget_es2</a><br>"
                newlinks_5ce.innerHTML += "<a href='Programmi20192020/text_5ce/Budget_esercizio_1.html'>Budget_esercizio_1</a><br>"
                newlinks_5ce.innerHTML += "<a href='Programmi20192020/text_5ce/Cambio.html'>Cambio</a><br>"
                newlinks_5ce.innerHTML += "<a href='Programmi20192020/text_5ce/Esercizio_Budget_100_coperti.html'>Esercizio_Budget_100_coperti</a><br>"
                newlinks_5ce.innerHTML += "<a href='Programmi20192020/text_5ce/Punteggi.html'>Punteggi</a><br>"
                newlinks_5ce.innerHTML += "<a href='Programmi20192020/text_5ce/Test_turismo_1.html'>Test_turismo_1</a><br>"
                newlinks_5ce.innerHTML += "<a href='Programmi20192020/text_5ce/Test_turismo_2.html'>Test_turismo_2</a><br>"
                newlinks_5ce.innerHTML += "<a href='Programmi20192020/text_5ce/Test_turismo_3.html'>Test_turismo_3</a><br>"
                newlinks_5ce.innerHTML += "<a href='Programmi20192020/text_5ce/Turismo.html'>Turismo</a><br>"
                newlinks_5ce.innerHTML += "<a href='Programmi20192020/text_5ce/Turismo2.html'>Turismo2</a><br>"
                newlinks_5ce.innerHTML += "<a href='Programmi20192020/text_5ce/Turismo_appunti_completo.html'>Turismo_appunti_completo</a><br>"
                