newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/5ce_turismo.html'>5ce_turismo.html</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/Esercizio_Turismo.html'>Esercizio_Turismo.html</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/fonti.html'>fonti.html</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/letture.html'>letture.html</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/Marketing.html'>Marketing.html</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/Organismi_interni.html'>Organismi_interni.html</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/punteggi.html'>punteggi.html</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/Turismo sostenibile.html'>Turismo sostenibile.html</a><br>"
                newlinks_5bs.innerHTML += "<a href='Programmi20192020/text_5bs/Turismo.html'>Turismo.html</a><br>"
                