newlinks_4ce.innerHTML += "<a href='Programmi20192020/text_4ce/000_programma 4ce.html'>000_programma 4ce</a><br>"
                newlinks_4ce.innerHTML += "<a href='Programmi20192020/text_4ce/Banca.html'>Banca</a><br>"
                newlinks_4ce.innerHTML += "<a href='Programmi20192020/text_4ce/c.html'>c</a><br>"
                newlinks_4ce.innerHTML += "<a href='Programmi20192020/text_4ce/domande_verifica_novembre.html'>domande_verifica_novembre</a><br>"
                newlinks_4ce.innerHTML += "<a href='Programmi20192020/text_4ce/ESERCIZI_INTERATTIVI.html'>ESERCIZI_INTERATTIVI</a><br>"
                newlinks_4ce.innerHTML += "<a href='Programmi20192020/text_4ce/es_anticipo_su_fatture.html'>es_anticipo_su_fatture</a><br>"
                newlinks_4ce.innerHTML += "<a href='Programmi20192020/text_4ce/punteggi.html'>punteggi</a><br>"
                newlinks_4ce.innerHTML += "<a href='Programmi20192020/text_4ce/sconto_es.html'>sconto_es</a><br>"
                newlinks_4ce.innerHTML += "<a href='Programmi20192020/text_4ce/todo.html'>todo</a><br>"
                newlinks_4ce.innerHTML += "<a href='Programmi20192020/text_4ce/verifica_finanziamenti.html'>verifica_finanziamenti</a><br>"
                