quiz = [{
	        "question"      :   "secondo un ordine di liquidità decrescente le attività dello Stato patrimoniale riclassificato presentano prima:",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['gli impieghi più liquidi', 'gli impieghi meno liquidi'],
	        "correct"       :   "gli impieghi più liquidi",
	        "explanation"   :   "",
	    },{
	        "question"      :   "L'attivo corrente nello SP riclassificato non comprende",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["i crediti esigibili oltre l'esercizio successivo", 'i ratei e i risconti attivi', 'le merci in magazzino', 'i crediti verso clienti'],
	        "correct"       :   "i crediti esigibili oltre l'esercizio successivo",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Le immobilizzazioni dello SP comprendono i",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["crediti esigibili oltre l'esercizio successivo", 'ratei e risconti', 'merci in magazzino', 'crediti a breve termine'],
	        "correct"       :   "crediti esigibili oltre l'esercizio successivo",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I diritti di brevetto sono",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['immobilizzazioni immateriali', 'immobilizzazioni materiali', 'crediti verso clienti', 'costi di assicurazione'],
	        "correct"       :   "immobilizzazioni immateriali",
	        "explanation"   :   "",
	    },{
	        "question"      :   "L'avviamento fa parte",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['delle immobilizzazione immateriali', 'delle immobilizzazione materiali', "dell'attivo circolante", 'delle immobilizzazioni finanziarie'],
	        "correct"       :   "delle immobilizzazione immateriali",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Le passività vengono riclassificate secondo la loro",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['esigibilità', 'liquidità'],
	        "correct"       :   "esigibilità",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I ratei e risconti passivi nella riclassificazione dello SP fanno parte delle",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['passività correnti', 'passività consolidate'],
	        "correct"       :   "passività correnti",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Le passività consolidate comprendono le fonti del capitale di debito che hanno scadenza",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["superiore all'anno", "inferiore all'anno"],
	        "correct"       :   "superiore all'anno",
	        "explanation"   :   "",
	    },{
	        "question"      :   "L'utile, ai fini dell'analisi di bilancio, la parte destinata ai soci",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['va tra le passività correnti', 'fa parte del patrimonio netto'],
	        "correct"       :   "va tra le passività correnti",
	        "explanation"   :   "",
	    },{
	        "question"      :   "A cosa serve l'analisi patrimoniale?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["A valutare l'equilibrio tra fonti e impieghi", "a valutare la redditività dell'impresa"],
	        "correct"       :   "A valutare l'equilibrio tra fonti e impieghi",
	        "explanation"   :   "",
	    },{
	        "question"      :   "L'elasticità degli impieghi è dato dal rapporto tra",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['attivo corrente e impieghi x 100', 'attivo immobilizzato e impieghi x 100'],
	        "correct"       :   "attivo corrente e impieghi x 100",
	        "explanation"   :   "",
	    },{
	        "question"      :   "L'utile destinato ai soci va",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['tra i debiti a breve termine', 'nel patrimonio netto', "nell'attivo circolante", 'nei debiti a lungo termine'],
	        "correct"       :   "tra i debiti a breve termine",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I ratei e risconti passivi nella riclas. dello SP vanno",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['tra i debiti a breve termine', 'tra i crediti a lungo termine'],
	        "correct"       :   "tra i debiti a breve termine",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Passività consolidata significa",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['debiti a lungo termine', 'debiti a breve termine'],
	        "correct"       :   "debiti a lungo termine",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Le passività correnti sono i debiti a breve termine",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['vero', 'falso'],
	        "correct"       :   "vero",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il reddito operativo è l'utile che spetta ai soci",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['falso', 'vero'],
	        "correct"       :   "falso",
	        "explanation"   :   "",
	    },{
	        "question"      :   "L'analisi patrimoniale valuta l'equilibrio tra",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['fonti e impieghi', 'costi e ricavi', 'entrate e uscite'],
	        "correct"       :   "fonti e impieghi",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Un'impresa è più elastica se",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['immobilizzazioni < attivo circolante', 'immobilizzazioni > attivo circolante'],
	        "correct"       :   "immobilizzazioni < attivo circolante",
	        "explanation"   :   "",
	    },{
	        "question"      :   "La composizione degli impieghi misura il grado di elasticità o rigidità del patrimonio aziendale",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['vero', 'falso'],
	        "correct"       :   "vero",
	        "explanation"   :   "",
	    },{
	        "question"      :   "L'elasticità degli impieghi si misura:",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['attivo corrente / totale impieghi x 100', 'attivo immobilizzato / tot. impieghi x 100'],
	        "correct"       :   "attivo corrente / totale impieghi x 100",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Le imprese ricettive e ristorative sono rigide",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['vero', 'falso'],
	        "correct"       :   "vero",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Nell'analisi delle fonti",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['si evidenzia il rapporto tra le fonti e il totale degli impieghi', 'si evidenzia il rapporto tra immobilizzazioni e attivo circolante'],
	        "correct"       :   "si evidenzia il rapporto tra le fonti e il totale degli impieghi",
	        "explanation"   :   "",
	    },{
	        "question"      :   "L'incidenza dei debiti a breve termine è dato da:",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['passività correnti / tot. impieghi x 100', 'passività consolidate / tot. impieghi x 100', 'capitale proprio / tot. impieghi x 100'],
	        "correct"       :   "passività correnti / tot. impieghi x 100",
	        "explanation"   :   "",
	    },{
	        "question"      :   "L'incidenza dei debiti a m/l termine è dato da:",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['passività consolidate / tot. impieghi x 100', 'passività correnti / tot. impieghi x 100', 'capitale proprio / tot. impieghi x 100'],
	        "correct"       :   "passività consolidate / tot. impieghi x 100",
	        "explanation"   :   "",
	    },{
	        "question"      :   "L'incidenza del capitale proprio è dato da:",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['capitale proprio / tot. impieghi x 100', 'capitale proprio / immobilizzazioni x 100', 'capitale proprio / attivo circolante x 100'],
	        "correct"       :   "capitale proprio / tot. impieghi x 100",
	        "explanation"   :   "",
	    },{
	        "question"      :   "L'indice di incidenza del capitale proprio è detto anche indice di autonomia finanziaria",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['vero', 'falso'],
	        "correct"       :   "vero",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Un'impresa è capitalizzata quanto l'indice di autonomia finanziaria",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['è almeno pari al 50%', 'è inferiore al 50%'],
	        "correct"       :   "è almeno pari al 50%",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il grado di capitalizzazione si può calcolare con",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['capitale proprio / capitale di debito', 'capitale di debito / attivo circolante'],
	        "correct"       :   "capitale proprio / capitale di debito",
	        "explanation"   :   "",
	    },{
	        "question"      :   "L'impresa è sottocapitalizzata se il grado di capitalizzazione",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['è inferiore a 1', 'è uguale a 1', 'è superiore a 1'],
	        "correct"       :   "è inferiore a 1",
	        "explanation"   :   "",
	    },];