quiz = [{
	        "question"      :   "Debiti v/fornitori: in quale prospetto di Bilancio andrà?",
	        "image"         :   "imgs/ratei.png",
	        "choices"       :   ['Stato patrimoniale', 'Conto economico'],
	        "correct"       :   "Stato patrimoniale",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Prodotti c/vendite: in quale prospetto di Bilancio andrà?",
	        "image"         :   "imgs/ratei.png",
	        "choices"       :   ['Conto economico', 'Stato patrimoniale'],
	        "correct"       :   "Conto economico",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Interessi passivi: in quale prospetto di Bilancio andrà?",
	        "image"         :   "imgs/ratei.png",
	        "choices"       :   ['Conto economico', 'Stato patrimoniale'],
	        "correct"       :   "Conto economico",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Ammortamenti: in quale prospetto di Bilancio andrà?",
	        "image"         :   "imgs/ratei.png",
	        "choices"       :   ['Conto economico', 'Stato patrimoniale'],
	        "correct"       :   "Conto economico",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Merci c/acquisti: in quale prospetto di Bilancio andrà?",
	        "image"         :   "imgs/ratei.png",
	        "choices"       :   ['Conto economico', 'Stato patrimoniale'],
	        "correct"       :   "Conto economico",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Capitale sociale: in quale prospetto di Bilancio andrà?",
	        "image"         :   "imgs/ratei.png",
	        "choices"       :   ['Stato patrimoniale', 'Conto economico'],
	        "correct"       :   "Stato patrimoniale",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Denaro in cassa: in quale prospetto di Bilancio andrà?",
	        "image"         :   "imgs/ratei.png",
	        "choices"       :   ['Stato patrimoniale', 'Conto economico'],
	        "correct"       :   "Stato patrimoniale",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Risconti attivi: in quale prospetto di Bilancio andrà?",
	        "image"         :   "imgs/ratei.png",
	        "choices"       :   ['Stato patrimoniale', 'Conto economico'],
	        "correct"       :   "Stato patrimoniale",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Merci in magazzino: in quale prospetto di Bilancio andrà?",
	        "image"         :   "imgs/ratei.png",
	        "choices"       :   ['Stato patrimoniale', 'Conto economico'],
	        "correct"       :   "Stato patrimoniale",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Banca x c/c: in quale prospetto di Bilancio andrà?",
	        "image"         :   "imgs/ratei.png",
	        "choices"       :   ['Stato patrimoniale', 'Conto economico'],
	        "correct"       :   "Stato patrimoniale",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Crediti v/clienti: in quale prospetto di Bilancio andrà?",
	        "image"         :   "imgs/ratei.png",
	        "choices"       :   ['Stato patrimoniale', 'Conto economico'],
	        "correct"       :   "Stato patrimoniale",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Fitti passivi: in quale prospetto di Bilancio andrà?",
	        "image"         :   "imgs/ratei.png",
	        "choices"       :   ['Conto economico', 'Stato patrimoniale'],
	        "correct"       :   "Conto economico",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Mutui passivi: in quale prospetto di Bilancio andrà?",
	        "image"         :   "imgs/ratei.png",
	        "choices"       :   ['Stato patrimoniale', 'Conto economico'],
	        "correct"       :   "Stato patrimoniale",
	        "explanation"   :   "",
	    },];