quiz = [{
	        "question"      :   "Gli obiettivi strategici si ottengono mediante il raggiungimento di obiettivi intermedi",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['vero', 'falso'],
	        "correct"       :   "vero",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il budget è un documento",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['preventivo', 'consuntivo'],
	        "correct"       :   "preventivo",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il budget evidenzia le risorse e gli obiettivi dell'anno",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['successivo', 'precedente'],
	        "correct"       :   "successivo",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I centri di responsabilità",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["è un'unità organizzativa cui sono affidate risorse e obiettivi", 'sono società di assicurazione'],
	        "correct"       :   "è un'unità organizzativa cui sono affidate risorse e obiettivi",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Nel budget a base zero si parte dai dati dell'anno precedente",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['falso', 'vero'],
	        "correct"       :   "falso",
	        "explanation"   :   "",
	    },{
	        "question"      :   "IL budget scorrevole prevede diversi scenari",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['falso', 'vero'],
	        "correct"       :   "falso",
	        "explanation"   :   "",
	    },{
	        "question"      :   "IL budget flessibile prevede diversi scenari",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['vero', 'falso'],
	        "correct"       :   "vero",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il budget incrementativo",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["fa previsioni in più o in meno rispetto all'anno precedente", 'non fa previsioni'],
	        "correct"       :   "fa previsioni in più o in meno rispetto all'anno precedente",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il bilancio è un documento consuntivo",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['vero', 'falso'],
	        "correct"       :   "vero",
	        "explanation"   :   "",
	    },{
	        "question"      :   "È perferibile adottare",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['costi ottenibili, non elevati, ma raggiungibili', 'costi ideali, molto efficienti, ma difficili da raggiungere'],
	        "correct"       :   "costi ottenibili, non elevati, ma raggiungibili",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I costi standard correnti si riferiscono ai livelli attuali di efficienza",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['vero', 'falso'],
	        "correct"       :   "vero",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Contiene i dati delle operazioni future sulle immobilizzazioni",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['budget degli investimenti', 'budget economico', 'budget finanziario'],
	        "correct"       :   "budget degli investimenti",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il budget economico è formato da tanti budget settoriali",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['vero', 'falso'],
	        "correct"       :   "vero",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Contiene i costi e i ricavi di competenza del periodo successivo",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['budget economico', 'budget finanziario'],
	        "correct"       :   "budget economico",
	        "explanation"   :   "",
	    },{
	        "question"      :   "È un vero e proprio bilancio di previsione",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['budget di esercizio', 'bilancio di esercizio'],
	        "correct"       :   "budget di esercizio",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Nel budget economico si parte dal budget degli acquisti",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['No, sì parte prima dal budget delle vendite', 'Sì, perché occorre conoscere prima i costi', 'No, perché si parte prima dal budget dei costi del personale'],
	        "correct"       :   "No, sì parte prima dal budget delle vendite",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Quanto guadagni per 3 mesi, stando aperti 26 giorni al mese, con 100 menu venduti al giorno a 10 €",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['78000', '39000', '10000'],
	        "correct"       :   "78000",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Quanto guadagni per 3 mesi, stando aperti 26 giorni al mese, con 50 menu venduti al giorno a 10 €",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['39000', '78000', '10000'],
	        "correct"       :   "39000",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Si articola nel budget delle fonti e degli impieghi",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Budget dei finanziamenti', 'Budget economico', 'Budget degli investimenti'],
	        "correct"       :   "Budget dei finanziamenti",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Efficienza",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['significa raggingere un obiettivo con minori costi possibili', 'è sinonimo di efficacia'],
	        "correct"       :   "significa raggingere un obiettivo con minori costi possibili",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Se i costi diretti sono il 30% del prezzo, il fattore è",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['3,33', '3', '30'],
	        "correct"       :   "3,33",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il metodo full costing prende come base del calcolo",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['il costo pieno', 'i soli costi diretti'],
	        "correct"       :   "il costo pieno",
	        "explanation"   :   "",
	    },];