quiz = [{
	        "question"      :   "La comunicazione serve a",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['tutte le risposte sono corrette', 'scambiare informazioni', 'diffondere idee', 'raggiungere gli stakeholder'],
	        "correct"       :   "tutte le risposte sono corrette",
	        "explanation"   :   "",
	    },{
	        "question"      :   "La comunicazione interna si rivolge a",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['i dirigenti', 'i fornitori', 'le banche', 'lo Stato'],
	        "correct"       :   "i dirigenti",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Le strategie riguardano il",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['breve periodo', 'lungo periodo'],
	        "correct"       :   "breve periodo",
	        "explanation"   :   "",
	    },{
	        "question"      :   "La comunicazione economico-finanziaria si rivolge soprattutto a",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['finanziatori', 'collettività', 'clienti', 'a tutte le categorie'],
	        "correct"       :   "finanziatori",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Le scritture elementari sono obbligatorie",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['falso', 'vero'],
	        "correct"       :   "falso",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I conti finanziari riguardano",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['strumenti di pagamento', 'valore dei beni acquistati', 'valore dei beni venduti'],
	        "correct"       :   "strumenti di pagamento",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I conti finanziari",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['non si devono valutare', 'si devono valutare'],
	        "correct"       :   "non si devono valutare",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Entrate ed uscite si rilevano nei conti",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['finanziari', 'economici'],
	        "correct"       :   "finanziari",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Costituiscono la contabilità generale",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['le scritture complesse', 'le scritture elementari'],
	        "correct"       :   "le scritture complesse",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Si rilevano le operazioni in ordine di data ne",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['giornale', 'mastro'],
	        "correct"       :   "giornale",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Contengono scritture sistematice",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['mastro', 'giornale'],
	        "correct"       :   "mastro",
	        "explanation"   :   "",
	    },{
	        "question"      :   "L'acquisto di una merce genera",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Iva a credito verso lo Stato', 'IVa a debito verso lo Stato'],
	        "correct"       :   "Iva a credito verso lo Stato",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Sono obbligatori",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['giornale e libro degli inventari', 'giornale e mastro', 'mastro e libro degli inventari'],
	        "correct"       :   "giornale e libro degli inventari",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il conto Banca x c/c è",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['finanziario', 'economico'],
	        "correct"       :   "finanziario",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il patrimonio netto è",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Attivo - passivo', 'Attivo + passivo', 'uguale al passivo'],
	        "correct"       :   "Attivo - passivo",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Banca x c/c: bonifico a favore di un fornitore",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['va in dare', 'va in avere'],
	        "correct"       :   "va in dare",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Nelle vendite:",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["l'iva è un debito verso lo Stato", "l'iva è un credito verso lo Stato"],
	        "correct"       :   "l'iva è un debito verso lo Stato",
	        "explanation"   :   "",
	    },{
	        "question"      :   "La liquidazione IVA",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Iva sugli acquisti + Iva sulle vendite', 'Iva sulle vendite - Iva sugli acquisti'],
	        "correct"       :   "Iva sugli acquisti + Iva sulle vendite",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il soggetto inciso dall'IVA è",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Il consumatore', "L'impresa"],
	        "correct"       :   "Il consumatore",
	        "explanation"   :   "",
	    },];