quiz = [{
	        "question"      :   "Denaro in cassa è un conto",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Finanziario', 'Economico'],
	        "correct"       :   "Finanziario",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Crediti v/clienti  è un conto",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Finanziario', 'Economico'],
	        "correct"       :   "Finanziario",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Merci c/acquisti  è un conto",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Economico', 'Finanziario'],
	        "correct"       :   "Economico",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Merci c/vendite  è un conto",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Economico', 'Finanziario'],
	        "correct"       :   "Economico",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Iva ns Credito  è un conto",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Finanziario', 'Economico'],
	        "correct"       :   "Finanziario",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Iva ns Debito  è un conto",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Finanziario', 'Economico'],
	        "correct"       :   "Finanziario",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Debiti v/fornitori è un conto",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Finanziario', 'Economico'],
	        "correct"       :   "Finanziario",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I debiti vanno in ",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['avere', 'dare'],
	        "correct"       :   "avere",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I costi vanno",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['dare', 'avere'],
	        "correct"       :   "dare",
	        "explanation"   :   "",
	    },{
	        "question"      :   "le entrate vanno in ",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['dare', 'avere'],
	        "correct"       :   "dare",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Nella Partita doppia dare e avere pareggiano",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['sempre', 'a volte'],
	        "correct"       :   "sempre",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Se dalla banca prelevo 100 euro",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['scrivo 100 in avere', 'scrivo 100 in dare'],
	        "correct"       :   "scrivo 100 in avere",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Quando pago un debito di 50 €",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['In debiti v/fornitori scrivo 50 € in dare', 'In debiti v/fornitori scrivo 50 € in avere'],
	        "correct"       :   "In debiti v/fornitori scrivo 50 € in dare",
	        "explanation"   :   "",
	    },{
	        "question"      :   "La liquidazione IVA è",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Iva a debito - Iva a credito', 'Iva a debito + Iva a credito'],
	        "correct"       :   "Iva a debito - Iva a credito",
	        "explanation"   :   "",
	    },{
	        "question"      :   "L'IVA la pagano definitivamente solo",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['i consumatori', 'le imprese'],
	        "correct"       :   "i consumatori",
	        "explanation"   :   "",
	    },];