quiz = [{
	        "question"      :   "Cosa dice l'art.10?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["L'ordinamento giuridico italiano si conforma alle norme del diritto internazionale generalmente riconosciute.", 'La Repubblica è una e indivisibile', 'Lo Stato e la Chiesa cattolica sono, ciascuno nel proprio ordine, indipendenti e sovrani.', 'La sovranità appartiene al popolo'],
	        "correct"       :   "L'ordinamento giuridico italiano si conforma alle norme del diritto internazionale generalmente riconosciute.",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cosa dice l'art.4, comma 2?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["Ogni cittadino ha diritto di svolgere un'attività che concorra al progresso della società", "L'Italia ripudia la guerra come strumento di offesa alla libertà degli altri popoli", 'La Repubblica promuove lo sviluppo della cultura e la ricerca scientifica e tecnica', 'La sovranità appartiene al popolo'],
	        "correct"       :   "Ogni cittadino ha diritto di svolgere un'attività che concorra al progresso della società",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cosa dice l'art.1, comma 1?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["L'Italia è una Repubblica fondata sul lavoro", 'La Repubblica è una e indivisibile', 'Sono elettori tutti i cittadini, uomini e donne, che hanno raggiunto la maggiore età', 'La Repubblica promuove lo sviluppo della cultura e la ricerca scientifica e tecnica'],
	        "correct"       :   "L'Italia è una Repubblica fondata sul lavoro",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cosa dice l'art.41?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["L'iniziativa economica privata è libera.", "L'Italia ripudia la guerra come strumento di offesa alla libertà degli altri popoli", 'Tutti i cittadini hanno pari dignità sociale', 'La Repubblica è una e indivisibile'],
	        "correct"       :   "L'iniziativa economica privata è libera.",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cosa dice l'art.2?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["La repubblica riconosce i diritti inviolabili dell'uomo", 'Tutti sono tenuti a concorrere alle spese pubbliche in ragione della loro capacità contributiva.', 'La Repubblica tutela con apposite norme le minoranze linguistiche', 'La Repubblica tutela il paesaggio e il patrimonio storico e artistico della Nazione.'],
	        "correct"       :   "La repubblica riconosce i diritti inviolabili dell'uomo",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cosa dice l'art.9, comma 2?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['La Repubblica tutela il paesaggio e il patrimonio storico e artistico della Nazione.', 'Tutti i cittadini hanno pari dignità sociale', 'Tutti sono tenuti a concorrere alle spese pubbliche in ragione della loro capacità contributiva.', 'La sovranità appartiene al popolo'],
	        "correct"       :   "La Repubblica tutela il paesaggio e il patrimonio storico e artistico della Nazione.",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cosa dice l'art.3?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Tutti i cittadini hanno pari dignità sociale', 'La Repubblica tutela con apposite norme le minoranze linguistiche', 'Tutte le confessioni religiose sono egualmente libere davanti alla legge', 'La sovranità appartiene al popolo'],
	        "correct"       :   "Tutti i cittadini hanno pari dignità sociale",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cosa dice l'art.5?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['La Repubblica è una e indivisibile', "L'Italia ripudia la guerra come strumento di offesa alla libertà degli altri popoli", 'La bandiera della Repubblica è il tricolore italiano: verde, bianco e rosso', 'Tutte le confessioni religiose sono egualmente libere davanti alla legge'],
	        "correct"       :   "La Repubblica è una e indivisibile",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cosa dice l'art.11?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["L'Italia ripudia la guerra come strumento di offesa alla libertà degli altri popoli", 'Il sistema tributario è informato a criteri di progressività.', 'La sovranità appartiene al popolo', 'Lo Stato e la Chiesa cattolica sono, ciascuno nel proprio ordine, indipendenti e sovrani.'],
	        "correct"       :   "L'Italia ripudia la guerra come strumento di offesa alla libertà degli altri popoli",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cosa dice l'art.12?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['La bandiera della Repubblica è il tricolore italiano: verde, bianco e rosso', 'Sono elettori tutti i cittadini, uomini e donne, che hanno raggiunto la maggiore età', "La Repubblica tutela la salute come fondamentale diritto dell'individuo e interesse della collettività, e garantisce cure gratuite agli indigenti.", 'La Repubblica tutela con apposite norme le minoranze linguistiche'],
	        "correct"       :   "La bandiera della Repubblica è il tricolore italiano: verde, bianco e rosso",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cosa dice l'art.7?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Lo Stato e la Chiesa cattolica sono, ciascuno nel proprio ordine, indipendenti e sovrani.', 'La Repubblica tutela con apposite norme le minoranze linguistiche', 'La sovranità appartiene al popolo', 'Sono elettori tutti i cittadini, uomini e donne, che hanno raggiunto la maggiore età'],
	        "correct"       :   "Lo Stato e la Chiesa cattolica sono, ciascuno nel proprio ordine, indipendenti e sovrani.",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cosa dice l'art.8?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Tutte le confessioni religiose sono egualmente libere davanti alla legge', 'La Repubblica promuove lo sviluppo della cultura e la ricerca scientifica e tecnica', 'La Repubblica tutela con apposite norme le minoranze linguistiche', 'Tutti sono tenuti a concorrere alle spese pubbliche in ragione della loro capacità contributiva.'],
	        "correct"       :   "Tutte le confessioni religiose sono egualmente libere davanti alla legge",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cosa dice l'art.34?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['La scuola è aperta a tutti.', 'La Repubblica promuove lo sviluppo della cultura e la ricerca scientifica e tecnica', 'La sovranità appartiene al popolo', 'La Repubblica tutela con apposite norme le minoranze linguistiche'],
	        "correct"       :   "La scuola è aperta a tutti.",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cosa dice l'art.4, comma 1?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['La Repubblica riconosce a tutti i cittadini il diritto al lavoro', 'Tutti sono tenuti a concorrere alle spese pubbliche in ragione della loro capacità contributiva.', 'La Repubblica tutela con apposite norme le minoranze linguistiche', 'La sovranità appartiene al popolo'],
	        "correct"       :   "La Repubblica riconosce a tutti i cittadini il diritto al lavoro",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cosa dice l'art.6?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['La Repubblica tutela con apposite norme le minoranze linguistiche', "La Repubblica tutela la salute come fondamentale diritto dell'individuo e interesse della collettività, e garantisce cure gratuite agli indigenti.", 'La sovranità appartiene al popolo', 'Il sistema tributario è informato a criteri di progressività.'],
	        "correct"       :   "La Repubblica tutela con apposite norme le minoranze linguistiche",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cosa dice l'art.9, comma 1?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['La Repubblica promuove lo sviluppo della cultura e la ricerca scientifica e tecnica', 'Il sistema tributario è informato a criteri di progressività.', "La Repubblica tutela la salute come fondamentale diritto dell'individuo e interesse della collettività, e garantisce cure gratuite agli indigenti.", 'Tutti sono tenuti a concorrere alle spese pubbliche in ragione della loro capacità contributiva.'],
	        "correct"       :   "La Repubblica promuove lo sviluppo della cultura e la ricerca scientifica e tecnica",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cosa dice l'art.32?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["La Repubblica tutela la salute come fondamentale diritto dell'individuo e interesse della collettività, e garantisce cure gratuite agli indigenti.", 'Sono elettori tutti i cittadini, uomini e donne, che hanno raggiunto la maggiore età', 'La sovranità appartiene al popolo', 'Tutti sono tenuti a concorrere alle spese pubbliche in ragione della loro capacità contributiva.'],
	        "correct"       :   "La Repubblica tutela la salute come fondamentale diritto dell'individuo e interesse della collettività, e garantisce cure gratuite agli indigenti.",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cosa dice l'art.53. comma 2?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Il sistema tributario è informato a criteri di progressività.', 'Sono elettori tutti i cittadini, uomini e donne, che hanno raggiunto la maggiore età', 'Tutti sono tenuti a concorrere alle spese pubbliche in ragione della loro capacità contributiva.', 'La sovranità appartiene al popolo'],
	        "correct"       :   "Il sistema tributario è informato a criteri di progressività.",
	        "explanation"   :   "",
	    },];