 
let quiz = [
{
	        "question"      :   "Il marketing mix riguarda:",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['marketing operativo', 'marketing strategico'],
	        "correct"       :   "marketing operativo",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Quanti intermediari ci sono nel CANALE di DISTRIBUZIONE BREVE",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['1', '0', '2'],
	        "correct"       :   "1",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il fattore con costi diretti al 30% del prezzo è",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['100/30', '30/100', '30 x 100', '100 x 30'],
	        "correct"       :   "100/30",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I costi diretti sono",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['i costi delle materie prime', 'i costi di amministrazione', 'i per la pubblicità'],
	        "correct"       :   "i costi delle materie prime",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Costi diretti 5 € (25% del prezzo), prezzo = ?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['20 €', '10 €', '15 €'],
	        "correct"       :   "20 €",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il prodotto è costituito da elementi",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['materiali e immateriali', 'solo materiali', 'solo immateriali'],
	        "correct"       :   "materiali e immateriali",
	        "explanation"   :   "",
	    },{
	        "question"      :   "la gamma comprende",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['tutti i prodotti', 'i prodotti di un certo tipo', 'i prodotti con lo stesso utilizzo', 'i prodotti di una linea'],
	        "correct"       :   "tutti i prodotti",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Le fasi del ciclo di vita del prodotto",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['lancio, sviluppo, maturità, declino', 'declino, lancio, sviluppo, maturità', 'maturità, lancio, sviluppo, declino', 'sviluppo, lancio, maturità, rilancio'],
	        "correct"       :   "lancio, sviluppo, maturità, declino",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Nella fase di lancio del prodotto i clienti sono:",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['clienti innovatori', 'adottanti iniziali', 'adottanti successivi', 'clienti ritardatari'],
	        "correct"       :   "clienti innovatori",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Nella fase di sviluppo del prodotto i clienti sono:",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['adottanti iniziali', 'clienti innovatori', 'adottanti successivi', 'clienti ritardatari'],
	        "correct"       :   "adottanti iniziali",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Nella fase di maturità  del prodotto i clienti si chiamano:",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['adottanti successivi', 'clienti innovatori', 'adottanti iniziali', 'clienti ritardatari'],
	        "correct"       :   "adottanti successivi",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Nella fase di declino del prodotto i clienti si chiamano",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['ritardatari', 'innovatori', 'iniziali', 'successivi'],
	        "correct"       :   "ritardatari",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Si punta sulla pubblicità:",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["nell'orientamento alle vendite", "nell'orientamento al prodotto", "nell'orientamento al mercato"],
	        "correct"       :   "nell'orientamento alle vendite",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Si punta a ridurre i costi nell'orientamento...",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['al prodotto', 'alle vendite', 'al mercato', 'al negozio'],
	        "correct"       :   "al prodotto",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Si punta a soddisfare il cliente nell'orientamento...",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['al mercato', 'alle vendite', 'al prodotto', 'al negozio'],
	        "correct"       :   "al mercato",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Si analizzano prima i gusti dei consumatori nell'orientamento...",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['al mercato', 'alle vendite', 'al prodotto', 'al negozio'],
	        "correct"       :   "al mercato",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I prezzi di penetrazione sono",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['bassi', 'alti', 'uguali alla concorrenza'],
	        "correct"       :   "bassi",
	        "explanation"   :   "",
	    },{
	        "question"      :   "i prezzi allineati sono",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['uguali alla concorrenza', 'bassi', 'alti'],
	        "correct"       :   "uguali alla concorrenza",
	        "explanation"   :   "",
	    },{
	        "question"      :   "i prezzi di scrematura sono",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['più alti', 'uguali alla concorrenza', 'più bassi'],
	        "correct"       :   "più alti",
	        "explanation"   :   "",
	    },{
	        "question"      :   "La Apple pratica prezzi",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['di scrematura', 'di penetrazione', 'uguali alla concorrenza'],
	        "correct"       :   "di scrematura",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Le imprese orientate al prodotto puntano",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['a ridurre i costi', 'a fidelizzare i clienti', 'sulla pubblicità'],
	        "correct"       :   "a ridurre i costi",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Le imprese orientate alle vendite puntano",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['sulla pubblicità', 'a ridurre i costi', 'a fidelizzare i clienti'],
	        "correct"       :   "sulla pubblicità",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Le imprese orientate al mercato puntano",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['a fidelizzare i clienti', 'a ridurre i costi', 'sulla pubblicità'],
	        "correct"       :   "a fidelizzare i clienti",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Nell'analisi interna si individuano",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['punti di forza e debolezza', 'opportunità e minacce'],
	        "correct"       :   "punti di forza e debolezza",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Weaknesses significa",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['punti di debolezza', 'punti di forza', 'opportunità', 'minacce'],
	        "correct"       :   "punti di debolezza",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Strengths significa",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['punti di forza', 'punti di debolezza', 'opportunità', 'minacce'],
	        "correct"       :   "punti di forza",
	        "explanation"   :   "",
	    },{
	        "question"      :   "threats significa",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['minacce', 'punti di debolezza', 'punti di forza', 'opportunità'],
	        "correct"       :   "minacce",
	        "explanation"   :   "",
	    },{
	        "question"      :   "SWOT significa",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['forza debolezza opportunità minacce', 'sudore sangue e lacrime', 'sicure welfare oracle tourism'],
	        "correct"       :   "forza debolezza opportunità minacce",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Le strategie di consolidamento si attua nelle fasi",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['di saturazione del mercato', 'favorevoli', 'sfavorevoli'],
	        "correct"       :   "di saturazione del mercato",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Con le strategie di ridimensionamento",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['si eliminano prodotti in perdita', 'si affronta una congiuntura economica favorevole'],
	        "correct"       :   "si eliminano prodotti in perdita",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Le strategie di espansione si definiscono per",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['in periodi favorevoli', 'in attesa di stagnazione', 'in periodi di crisi'],
	        "correct"       :   "in periodi favorevoli",
	        "explanation"   :   "",
	    },{
	        "question"      :   "In periodi favorevoli:",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['si segue una strategia di espansione', 'si segue una strategia di consolidamento', 'si segue una strategia ridimensionamento'],
	        "correct"       :   "si segue una strategia di espansione",
	        "explanation"   :   "",
	    },{
	        "question"      :   "L'ambiente esterno comprende:",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["l'ambiente specifico e generale", "l'ambiente specifico e interno"],
	        "correct"       :   "l'ambiente specifico e generale",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il marketing mix comprende",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['le quattro p', 'le strategie di scelta', 'le strategie di analisi', 'il posizionamento'],
	        "correct"       :   "le quattro p",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Vision",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["scenario futuro cui l'impresa tende", "scopo che l'impresa vuole realizzare"],
	        "correct"       :   "scenario futuro cui l'impresa tende",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Mission",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["scopo che l'impresa vuole realizzare nel medio-lungo termine", "scenario futuro cui l'impresa tende"],
	        "correct"       :   "scopo che l'impresa vuole realizzare nel medio-lungo termine",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Sono strenghts:",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['localizzazione favorevole', 'congiuntura economica favorevole', 'rischio di ingresso di nuovi concorrenti', 'servizi scadenti'],
	        "correct"       :   "localizzazione favorevole",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Sono Weaknesses:",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['servizi scadenti', 'localizzazione favorevole', 'congiuntura economica favorevole', 'rischio di ingresso di nuovi concorrenti'],
	        "correct"       :   "servizi scadenti",
	        "explanation"   :   "",
	    },{
	        "question"      :   "È una opportunità:",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['una fase di crescita economica', 'la localizzazione favorevole', 'ingresso di nuovi concorrenti', 'qualità scadente del prodotto'],
	        "correct"       :   "una fase di crescita economica",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Sono delle minaccce:",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['ingresso di nuovi concorrenti', 'congiuntura economica favorevole', 'localizzazione sfavorevole', 'prodotto datato'],
	        "correct"       :   "ingresso di nuovi concorrenti",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Un vantaggio competitivo è...",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['La capacità di offrire prezzi più bassi o caratteristiche diverse', 'Avere molti concorrenti', 'una fase congiunturale favorevole', 'Avere clienti poco fedeli'],
	        "correct"       :   "La capacità di offrire prezzi più bassi o caratteristiche diverse",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Verifica il raggiungimento degli obiettivi:",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['il controllo di gestione', "l'analisi SWOT", 'le analisi di mercato'],
	        "correct"       :   "il controllo di gestione",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Raggiungere gli obiettivi con minori costi è",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['efficienza', 'efficacia'],
	        "correct"       :   "efficienza",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Efficacia ed efficienza hanno lo stesso significato?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['No, efficienza significa efficacia + ottimizzazione dei costi', 'Sì, sono sinomini'],
	        "correct"       :   "No, efficienza significa efficacia + ottimizzazione dei costi",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Un'impresa è efficace se",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['raggiunge gli obiettivi, ma non minimizza i costi', 'raggiunge gli obiettivi e minimizza i costi'],
	        "correct"       :   "raggiunge gli obiettivi, ma non minimizza i costi",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il controllo di gestione",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['verifica lo scostamento tra dati preventivi e consuntivi', 'si attua prima di definire gli obiettivi', 'comporta sempre una modifica della pianificazione', 'definisce gli obiettivi strategici'],
	        "correct"       :   "verifica lo scostamento tra dati preventivi e consuntivi",
	        "explanation"   :   "",
	    },
];