quiz = [{
	        "question"      :   "Definisci la domanda turistica.",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['insieme delle richieste di servizi turistici.', 'insieme dei servizi turistici offerti dalle imprese del settore.'],
	        "correct"       :   "insieme delle richieste di servizi turistici.",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Quali sono gli Indicatori della dimensione della domanda turistica",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['arrivi, presenze, permanenza media, tasso di propensione turistica.', 'tasso di ricettività e densità ricettiva'],
	        "correct"       :   "arrivi, presenze, permanenza media, tasso di propensione turistica.",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cosa sono gli arrivi",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['i visitatori di una destinazione', 'i residenti'],
	        "correct"       :   "i visitatori di una destinazione",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cosa sono le presenze",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['le notti trascorse dai turisti', 'gli arrivi di turisti'],
	        "correct"       :   "le notti trascorse dai turisti",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Come si calcola la permanenza media",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['presenze / arrivi', 'arrivi / presenze'],
	        "correct"       :   "presenze / arrivi",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Come si trova il tasso di propensione turistica:",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['viaggi : abitanti x 100', 'viaggi / kmq'],
	        "correct"       :   "viaggi : abitanti x 100",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Quali sono gli indicatori della dimensione dell'offerta turistica?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['tasso di ricettività e densità ricettiva', 'presenze / arrivi', 'arrivi / presenze'],
	        "correct"       :   "tasso di ricettività e densità ricettiva",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Qual è la formula del tasso di ricettività",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['pl/abitanti*100', 'pl/abitanti', 'pl/kmq'],
	        "correct"       :   "pl/abitanti*100",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cos'è il PIL?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['prodotto interno lordo', 'parere interno laterale', 'Paese italiano lordo'],
	        "correct"       :   "prodotto interno lordo",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Quanti sono gli occupati nel settore turistico",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['2.000.000', '1.000.000', '5.000.000'],
	        "correct"       :   "2.000.000",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cos'è la bilancia turistica?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["documento che rileva consumi dei turisti stranieri in Italia e Italiani all'estero", 'Documento che rileva le importazione e le esportazioni'],
	        "correct"       :   "documento che rileva consumi dei turisti stranieri in Italia e Italiani all'estero",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Com'è il saldo della bilancia turistica",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['attivo', 'passivo', 'in pareggio'],
	        "correct"       :   "attivo",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Flussi turistici in Italia, aumentano o diminuiscono?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['aumentano', 'diminuiscono', 'sono invariati'],
	        "correct"       :   "aumentano",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Quali sono le mete preferite da italiani?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['destinazioni balneari', "città d'arte del centro nord"],
	        "correct"       :   "destinazioni balneari",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Qual è percentuale dei turisti dall'Europa in Italia",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['70%', '30%', '10%'],
	        "correct"       :   "70%",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Si recano per turismo business più in Italia rispetto ai Paesi asiatici",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Falso', 'Vero'],
	        "correct"       :   "Falso",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Che posto occupa l'Italia tra gli arrivi internazionali?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['5', '4', '1', '3'],
	        "correct"       :   "5",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Quale percentuale di PIL è dovuta al turismo?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['10%', '20%', '30%', '40%'],
	        "correct"       :   "10%",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Chi ha la competenza a legiferare in materia di turismo? Lo Stato o le Regioni?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Regioni', 'stato'],
	        "correct"       :   "Regioni",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Quali sono gli enti di promozione del turismo?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['APT e Pro loco a livello locale e Enit (Agenzia nazionale del turismo)', "ISTAT, La Banca d'ITALIA, l'ONT, e l'ISNART"],
	        "correct"       :   "APT e Pro loco a livello locale e Enit (Agenzia nazionale del turismo)",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Qual è la legge fondamentale dello Stato?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['La Costituzione', 'Lo Statuto Albertino'],
	        "correct"       :   "La Costituzione",
	        "explanation"   :   "",
	    },{
	        "question"      :   "La Costituzione può essere modificata?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Si, con le leggi costituzionali', 'Si, con le leggi ordinarie', 'No'],
	        "correct"       :   "Si, con le leggi costituzionali",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Chi approva le leggi ordinarie?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Parlamento', 'Governo', 'Regioni'],
	        "correct"       :   "Parlamento",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Come vengono approvate le leggi ordinarie?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['In tre fasi', 'In due fasi', 'In una sola fase'],
	        "correct"       :   "In tre fasi",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I decreti leggi sono approvati dal Governo o dal Parlamento?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Governo, in caso di urgenza.', 'Parlamento, in caso di urgenza.'],
	        "correct"       :   "Governo, in caso di urgenza.",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Di cosa c'è bisogno per approvare i ",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['decreti legislativi?', 'Di una legge delega approvata dal Parlamento', 'Di un decreto legge approvato dal Parlamento'],
	        "correct"       :   "decreti legislativi?",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cosa bisogna fare perché i decreti legge non perdano di efficacia?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Devono essere convertiti in legge approvata dal Parlamento entro 60 giorni. ', 'Devono essere convertiti in legge approvata dal Parlamento entro 30 giorni.'],
	        "correct"       :   "Devono essere convertiti in legge approvata dal Parlamento entro 60 giorni. ",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Chi approva le leggi regionali? Il Governo, Il Parlamento o i Consigli regionali?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Il consiglio regionale', 'Il Parlamento', 'Il Governo'],
	        "correct"       :   "Il consiglio regionale",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I regolamenti governativi da chi sono approvati?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Dal Governo.', 'Dalle Regioni'],
	        "correct"       :   "Dal Governo.",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I regolamenti governativi sono allo stesso livello delle leggi ordinarie?",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Si', 'no, sono subordinate alle leggi ordinarie.'],
	        "correct"       :   "Si",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Cosa sono gli usi e consuetudini.",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Fonti non scritte', 'Fonti scritte'],
	        "correct"       :   "Fonti non scritte",
	        "explanation"   :   "",
	    },];