quiz = [{
	        "question"      :   "I turisti viaggiano in modo irregolare",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['vero', 'falso'],
	        "correct"       :   "vero",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I turisti viaggiano per ottenere un reddito",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['falso', 'vero'],
	        "correct"       :   "falso",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I turisti pernottano almeno un giorno",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['vero', 'falso'],
	        "correct"       :   "vero",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Gli escursionisti",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['pernottano', 'non pernottano'],
	        "correct"       :   "pernottano",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I viaggi leisure sono viaggi di piacere",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['vero', 'falso'],
	        "correct"       :   "vero",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il turismo contrende le relazioni tra",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['turisti, ambiente, residenti e operatori economici del settore', 'turisti e operatori economici del settore'],
	        "correct"       :   "turisti, ambiente, residenti e operatori economici del settore",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il turismo produttivo è formato da",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['operatori economici del settore', 'turisti', 'residenti', 'ambiente'],
	        "correct"       :   "operatori economici del settore",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I turisti italiani che viaggiano solo in Italia fanno parte del turismo",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['domestico', 'interno', 'nazionale', 'internazionale'],
	        "correct"       :   "domestico",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Turisti italiani in ITALIA, turismo",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['interno', 'domestico', 'nazionale', 'internazionale'],
	        "correct"       :   "interno",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Turisti italiani in ITALIA ed ESTERO, turismo",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['nazionale', 'domestico', 'interno', 'internazionale'],
	        "correct"       :   "nazionale",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Turisti italiani e stranieri che oltrepassano la frontiera, turismo",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['internazionale', 'domestico', 'interno', 'nazionale'],
	        "correct"       :   "internazionale",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Attività offerte al turista in entrata",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['turismo produttivo incoming', 'turismo produttivo outgoing'],
	        "correct"       :   "turismo produttivo incoming",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Attività offerte al turista in uscita",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['turismo produttivo outgoing', 'turismo produttivo incoming'],
	        "correct"       :   "turismo produttivo outgoing",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Effetti negativi del turismo per i residenti",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['inquinamento ed aumento dei prezzi', 'riduzione del reddito', "riduzione dell'occupazione", 'peggioramento del livello di benessere'],
	        "correct"       :   "inquinamento ed aumento dei prezzi",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il turismo sostenibile mira a",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["favorire un turismo che non altera l'ambiente", 'sostenere le imprese che inquinano'],
	        "correct"       :   "favorire un turismo che non altera l'ambiente",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il bisogno è",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['uno stato di insoddisfazione', 'uno stato di soddisfazione'],
	        "correct"       :   "uno stato di insoddisfazione",
	        "explanation"   :   "",
	    },{
	        "question"      :   "La quantià di un certo prodotto realizzato dalle imprese",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["Costituiscono l'offerta di quel prodotto", 'Costituiscono la domanda di quel prodotto'],
	        "correct"       :   "Costituiscono l'offerta di quel prodotto",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Somma delle richieste della clienti di un prodotto",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['Domanda', 'Offerta'],
	        "correct"       :   "Domanda",
	        "explanation"   :   "",
	    },{
	        "question"      :   "L'elasticità della domanda è data dal rapporto tra variazione della domanda e variazione del prezzo",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['vero', 'falso'],
	        "correct"       :   "vero",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Presenze fratto arrivi uguale",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['permanenza media', 'permanenza netta'],
	        "correct"       :   "permanenza media",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Viaggi fratto abitanti =",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['tasso di propensione turistica', 'tasso di ricettività'],
	        "correct"       :   "tasso di propensione turistica",
	        "explanation"   :   "",
	    },{
	        "question"      :   "posti letto fratto kilometri =",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['densità ricettiva', 'tasso di ricettività'],
	        "correct"       :   "densità ricettiva",
	        "explanation"   :   "",
	    },{
	        "question"      :   "tasso di ricettività =",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['posti letto fratto abitanti', 'posti letto fratto kilometri', 'presenze fratto arrivi'],
	        "correct"       :   "posti letto fratto abitanti",
	        "explanation"   :   "",
	    },{
	        "question"      :   "nel prodotto turistico, il clima fa parte degli",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['elementi primari', 'elementi di supporto'],
	        "correct"       :   "elementi primari",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I ristoranti fanno parte, nel prodotto turistico, degl elementi",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['di supporto', 'primari'],
	        "correct"       :   "di supporto",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Tra domanda e prezzo dei servizi turistici",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["c'è un rapporto di proporzionalità indiretta", "c'è un rapporto di proporzionalità diretta"],
	        "correct"       :   "c'è un rapporto di proporzionalità indiretta",
	        "explanation"   :   "",
	    },];