import random
import os




def add_questions():
	''' creates a string with all call to input with questions and answer to be shown '''


	# ========= INSERIRE DOMANDE QUI SEGUITE DA RISPOSTA IN OGNI TUPLA ===
	# Tips: create a script to generate questions in a tuple and add here them
	lista_domande = [
		("Capitale italiana", "roma#vienna")
	]

	# creating the input("domanda", "risposta") series of call
	inp = ""
	for d in lista_domande:
		inp += f"""input("{d[0]}", "{d[1]}");\n"""

	return inp



def show():
	html = """
<style>
	.fontbig {
		font-size: 1.5em;
	}
 
body, html {
 background: #ECEDEF;
 margin-left: 10%;
 margin-right: 10%;
 padding: 0;
}
 

</style>
<!--<html oncontextmenu="return false;">-->
<script>

// ======================== CHECK ======================= >


const rightcolor = 'yellow'
const wrongcolor = "red";

function check(casella, giusta, num){
	// giusta is "1#2#3" and is splitted into a list of strings, then check if in this list there is the user input 
	let lista_esatte = giusta.split("#"); // right answers
	let user_input = casella.value;       // user input
	if (lista_esatte.includes(user_input.toLowerCase())){
		casella.style.background = rightcolor; // turns yellow if right
		return casella.value;
	}
	else{
		casella.style.background = wrongcolor; // turn red if wrong
	}
	console.log(giusta);                         // check for debug
	// console.log(casella.value.split("#));
} // ====================================== CHECK === !

function print_it(parola){
	if (soluzioni.innerHTML.includes(parola)){
	}
	else {
    	soluzioni.innerHTML += " - " + parola;
	}
}

var countdom = 1;
function input(domanda, giusta){
	var dom_h2 = "<table style='background:#fcab41;'><td><p class='fontbig' style='color: blue'>" + countdom++ + " " + domanda;
	var part1 = dom_h2 + "<br><i style='color:red'>rispondi nella casella sottostante e poi premi invio</i><br><input id='casella' class='fontbig' type=text class='t1' placeholder='?...' onchange=\\"if (check(this,'";
	part1 += giusta + "')){print_it(this.value)};\\" style='text-align:right'/></center></p></table>";
	document.write(part1);
	}
	

x = document.getElementsByClassName('t1');
for (i of x){
    i.value = "";
}

</script>
<!--         Here starts the html (only title)  -->
<h1>TITOLO</h1>

<!-- here starts the script to add input("question", "answer") generated by add_questions() in python -->
<script>
		"""
	# title to appear on top
	title = "Capitali d'Italia"

	# creates all the input("question", "answer") string
	html += add_questions()
	# close the script tag
	html += "</script>"
	html = html.replace("TITOLO", title)
	with open("fabbisogno2.html", "w", encoding="utf-8") as file:
		file.write(html)
	os.startfile("fabbisogno2.html")

show()