listanomi = [
		"5ae - scegli un nome da questa lista",
        "Breglia",
        "Cammarano_D",
        "Cammarano_N",
        "Costantini",
        "Del Verme,",
        "Esposito",
        "Fontana",
        "Garofalo",
        "Giordano",
        "Grimaldi",
        "Lista",
        "Malzone",
        "Mandia",
        "Marchesani",
        "Musto",
        "Ruocco",
        "Santoro",
        "Scola_M",
        "SCOLA_V",
            ];